#!/bin/sh -

#XPROFILE_SYSTEM="/etc/xprofile"
#test -f "${XPROFILE_SYSTEM}" && source "${XPROFILE_SYSTEM}"
XPROFILE_HOME="${XDG_CONFIG_HOME}/X11/Xprofile"
test -f "${XPROFILE_HOME}" && source "${XPROFILE_HOME}"

